//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ItemAssistant.rc
//
#define IDC_MYICON                      2
#define IDD_FORMVIEW                    101
#define IDD_PLAYERSHOP                  101
#define IDD_ITEMASSISTANT_DIALOG        102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDR_MAINFRAME                   128
#define IDR_INVENTORY_VIEW              129
#define IDR_DEBUG_VIEW                  130
#define IDD_MSG_FORM                    130
#define IDD_MSG_FORM1                   131
#define IDD_BOT_FORM                    131
#define IDS_AUNO_ITEMREF_URL            131
#define IDD_INV_FIND                    132
#define IDS_JAYDEE_ITEMREF_URL          132
#define IDR_INV_ACCEL                   133
#define IDD_PATTERN_MATCHER             134
#define IDR_PB_ACCEL                    135
#define IDD_ITEM_INFO                   136
#define IDD_WEB                         140
#define IDR_HTML1                       141
#define IDR_HTML2                       142
#define IDR_TRAY_POPUP                  143
#define IDR_ITEM_POPUP                  144
#define IDC_EDIT2                       1001
#define IDC_LIST1                       1002
#define IDC_EDIT1                       1003
#define IDC_EDIT3                       1004
#define IDC_BUTTON1                     1005
#define IDC_COMBO1                      1006
#define IDC_ITEMTEXT                    1007
#define IDC_CHARCOMBO                   1008
#define IDC_STATIC_TOON                 1009
#define IDC_PIECES                      1011
#define IDC_NOVI                        1012
#define IDC_PBCOMBO                     1013
#define IDC_PARTIALS                    1014
#define IDC_COMPLETE                    1015
#define IDC_CHECK5                      1017
#define IDC_COMPLETABLE                 1018
#define IDC_READY                       1019
#define IDC_LIST2                       1021
#define IDC_SQL_EDIT                    1022
#define IDC_LISTVIEW                    1023
#define IDC_AUNO                        1024
#define IDC_AODB                        1025
#define IDC_IE_PLACEHOLDER              1028
#define IDC_SHOW_ALL                    1029
#define IDC_PROGRESS                    1030
#define IDC_SHOW_PARTIALS               1031
#define IDC_VERSION                     1031
#define IDC_TREE1                       1032
#define ID_Menu                         32771
#define ID_VIEW_INVENTORY               32772
#define ID_VIEW_MESSAGES                32773
#define ID_VIEW_INFOPANEL               32778
#define ID_INV_FIND                     32782
#define ID_INV_FIND_HIDE                32784
#define ID_PB_FILTER                    32786
#define ID_PB_FILTER_HIDE               32787
#define ID_INFO                         32789
#define ID_TRAYMENU_SHOW                32791
#define ID_TRAYMENU_                    32792
#define ID_TRAYMENU_ABOUTITEMASSISTANT  32793
#define ID_TRAY_TOGLE                   32795
#define ID_COPY_AUNO_ITEMREF            32800
#define ID_COPY_JAYDEE_ITEMREF          32801
#define ID_COPY_BB_ITEMREF              32802
#define ID_COPY_AO_ITEMREF              32803
#define ID_COPYITEMASLINKTOAUNO_COPYITEMASLINKTOAUNO 32804
#define ID_ITEMCONTEXTMENU_COPYITEMHTLMLINK 32805
#define ID_COPYITEMHTLMLINK_AUNO        32806
#define ID_COPYITEMHTLMLINK_AOMAINFRAME 32807
#define ID_ITEMCONTEXTMENU_COPYITEMVBBLINK 32808
#define ID_COPYITEMVBBLINK_AUNO         32809
#define ID_COPYITEMVBBLINK_AOMAINFRAME  32810
#define ID_COPY_AUNO_ITEMREF_VBB        32811
#define ID_COPY_JAYDEE_ITEMREF_VBB      32812
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_TRAY_SHOW                    0xE802
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
